version: '3'

services:

  php:
    container_name: "php"
    build: ../laravel
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_DATABASE=laravel
      - DB_PASSWORD=2t9k51hP
    volumes:
      - ../laravel:/var/www/laravel
      - ../supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ../supervisor/tasks.conf:/etc/supervisor/conf.d/poker-parsefile.conf
  nginx_b:
    container_name: "nginx_b"
    build: ../nginx
    volumes:
      - ../nginx/conf_b.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/logs_b/:/var/log/nginx
    ports:
      - "27000:80"
    depends_on:
      - php
  nginx_f:
    container_name: "nginx_f"
    build: ../nginx
    volumes:
      - ../nginx/conf_f.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/logs_f/:/var/log/nginx
    ports:
      - "27001:80"
    depends_on:
      - php
  nuxt:
    container_name: "nuxt"
    build: ../nuxt
    volumes:
      - ../nuxt:/var/www/nuxt
    ports:
      - "3000:3000"
    environment:
      - API_URL=https://nginx_b
  mysql:
    image: mysql
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/scripts:/mysql/scripts
    environment:
      MYSQL_ROOT_PASSWORD: 2t9k51hP
      MYSQL_DATABASE: laravel
  supervisor:
    container_name: "supervisor"
    build: ../laravel
    ports:
      - 27002:9001
    volumes:
      - ../laravel:/var/www/laravel
      - ../supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ../supervisor/tasks.conf:/etc/supervisor/conf.d/poker-parsefile.conf
    command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf" ]